### ISSUE TITLE
node-cron destroy() is not a function

### ISSUE THREAD

**Issue by whitesimian** [node-cron/node-cron#311]
```
let test = cron.schedule('*/1 * * * * *', () => {
       console.log('Message node-cron')
})
test.destroy()
```

```
TypeError: test.destroy is not a function
```

In the documentation it's listed as a function.

**Comment by FTheron** [comment]
@whitesimian [289](https://github.com/node-cron/node-cron/pull/289)
Looks like the documentation needs to be updated.

**Comment by movingelectrons** [comment]
how does one remove a job ?  .destroy() is not a function.. .stop does stop a job but it persists .getTasks() shows it indefinitely?

**Comment by whitesimian** [comment]
> how does one remove a job ?

.destroy() works fine in the node-cron version 2.0.3
